[book]
title = "Developement Environment Setup For Android Linux"
authors = ["Aung Myat Moe (@amm834)"]
description = "To build applications from Android Linux"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/amm834/Development-Environment-Setup-For-Android"
git-repository-icon = " fa-github"

[output.html.print]
enable = true